apiVersion: v2
name: hub
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: datahub
    version: 0.4.19
    condition: datahub.enabled
    repository: https://helm.datahubproject.io
