apiVersion: v2
name: storage
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - alias: csi
    version: 4.6.0
    name: csi-driver-nfs
    condition: csi.enabled
    repository: "https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts"
