apiVersion: v1
kind: PersistentVolume
metadata:
  name: ai-translate-pv
spec:
  storageClassName: local
  accessModes: [ "ReadWriteMany" ]
  capacity:
    storage: 24Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /kube/ecommerce/ai/huggingface/hub
  nodeAffinity:
    {{- .Values.master.volume | toYaml | nindent 6 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: translate-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: local
  accessModes: [ "ReadWriteMany" ]
  resources:
    requests:
      storage: 24Gi
  volumeName: ai-translate-pv
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: translate-config
  namespace: {{ .Release.Namespace }}
data:
  MODEL_ID: "google/madlad400-3b-mt"
  CUDA_MEMORY_FRACTION: "0.9"
  MAX_TOTAL_TOKENS: "1024"
  HOSTNAME: "0.0.0.0"
  PORT: "80"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: translate
  namespace: {{ .Release.Namespace }}
  labels:
    app: translate
spec:
  selector:
    matchLabels:
      app: translate
  replicas: 1
  template:
    metadata:
      labels:
        app: translate
    spec:
      containers:
        - name: translate
          image: ghcr.io/huggingface/text-generation-inference:2.2.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: translate-config
          volumeMounts:
            - mountPath: /data
              name: translate
      volumes:
        - name: translate
          persistentVolumeClaim:
            claimName: translate-pvc
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nvidia.com/gpu.count
                    operator: Gt
                    values:
                      - "0"
---
apiVersion: v1
kind: Service
metadata:
  name: translate
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
  selector:
    app: translate
