apiVersion: v1
kind: PersistentVolume
metadata:
  name: datahub-zookeeper-0
  namespace: hub
spec:
  storageClassName: nfs
  nfs:
    server: 192.168.1.8
    path: /kube/ecommerce/hub/datahub/zookeeper-0
  capacity:
    storage: 8Gi
  accessModes: [ "ReadWriteOnce" ]
  claimRef:
    namespace: hub
    name: data-prerequisites-zookeeper-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datahub-kafka-broker-0
  namespace: hub
spec:
  storageClassName: nfs
  nfs:
    server: 192.168.1.8
    path: /kube/ecommerce/hub/datahub/kafka-broker-0
  capacity:
    storage: 8Gi
  accessModes: [ "ReadWriteOnce" ]
  claimRef:
    namespace: hub
    name: data-prerequisites-kafka-broker-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datahub-mysql-0
  namespace: hub
spec:
  storageClassName: nfs
  nfs:
    server: 192.168.1.8
    path: /kube/ecommerce/hub/datahub/mysql-0
  capacity:
    storage: 8Gi
  accessModes: [ "ReadWriteOnce" ]
  claimRef:
    namespace: hub
    name: data-prerequisites-mysql-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datahub-elasticsearch-0
  namespace: hub
spec:
  storageClassName: nfs
  nfs:
    server: 192.168.1.8
    path: /kube/ecommerce/hub/datahub/elasticsearch-0
  capacity:
    storage: 30Gi
  accessModes: [ "ReadWriteOnce" ]
  claimRef:
    namespace: hub
    name: elasticsearch-master-elasticsearch-master-0
---
