apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  mysql-password: "password"
  mysql-root-password: "admin"
  mysql-replication-password: "password"
---
apiVersion: v1
kind: Secret
metadata:
  name: datahub-ingestion-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  # datahub ingest deploy --name Iceberg --schedule "0 * * * *" -c /etc/datahub/ingestion-secret-files/iceberg.dhub.yaml
  iceberg.dhub.yaml: |
    source:
      type: iceberg
      config:
        env: DEV
        catalog:
          type: rest
          name: iceberg
          config:
            uri: http://iceberg.io
            s3.endpoint: http://lakehouse.io
            s3.access-key-id: admin
            s3.secret-access-key: password
            warehouse: s3a://ecommerce/iceberg/
        platform_instance: iceberg

  # datahub ingest deploy --name Warehouse --schedule "0 * * * *" -c /etc/datahub/ingestion-secret-files/warehouse.dhub.yaml
  warehouse.dhub.yaml: |
    source:
      type: postgres
      config:
        env: DEV
        host_port: warehouse.io:5432
        database: ecommerce
        username: admin
        password: password

  # datahub ingest deploy --name Kafka --schedule "0 * * * *" -c /etc/datahub/ingestion-secret-files/kafka.dhub.yaml
  kafka.dhub.yaml: |
    source:
      type: kafka
      config:
        env: DEV
        platform_instance: kafka
        connection:
          bootstrap: "cluster-kafka-brokers.kafka:9092"
          schema_registry_url: http://schema-registry.kafka:8081
        topic_patterns:
          deny:
            - ^_.*
            - .*-configs
            - .*-offsets
            - .*-status
