apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-pv-0
spec:
  capacity:
    storage: 8Gi
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: storage
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /kube/ecommerce/io/storage/storage-pv-0
  nodeAffinity:
{{ .Values.master.volume | toYaml | nindent 4 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-pvc-0
  namespace: io
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem
  storageClassName: storage
  volumeName: storage-pv-0
---
