apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: document
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: document-pv-0
spec:
  capacity:
    storage: 4Gi
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: document
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: document-pvc-0  # reserved
  hostPath:
    path: /kube/ecommerce/io/document/document-pv-0
  nodeAffinity:
{{ .Values.master.volume | toYaml | nindent 4 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: document-pvc-0
  namespace: io
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  volumeMode: Filesystem
  storageClassName: document
  volumeName: document-pv-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-document-pv-0
spec:
  capacity:
    storage: 4Gi
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: document
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: datadir-document-0  # reserved
  hostPath:
    path: /kube/ecommerce/io/document/datadir-document-pv-0
  nodeAffinity:
{{ .Values.master.volume | toYaml | nindent 4 }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-document-pv-1
spec:
  capacity:
    storage: 4Gi
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: document
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: datadir-document-1  # reserved
  hostPath:
    path: /kube/ecommerce/io/document/datadir-document-pv-1
  nodeAffinity:
{{ .Values.master.volume | toYaml | nindent 4 }}
---
