apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  mongodb-passwords: "password"
  mongodb-root-password: "password"
  mongodb-metrics-password: "password"
  mongodb-replica-set-key: "replica"
