apiVersion: v1
kind: Service
metadata:
  name: trino
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/name: trino
    app.kubernetes.io/component: coordinator
    app.kubernetes.io/instance: {{ .Release.Namespace }}
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
