apiVersion: v2
name: sql
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: trino
    version: 0.25.0
    condition: trino.enabled
    repository: https://trinodb.github.io/charts/
