apiVersion: v2
name: visual
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: superset
    version: 0.12.11
    condition: superset.enabled
    repository: http://apache.github.io/superset/

  - alias: opensearch
    version: 2.19.0
    name: opensearch-dashboards
    condition: opensearch.enabled
    repository: https://opensearch-project.github.io/helm-charts
