apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: public
  namespace: {{ .Release.Namespace }}
spec:
  addresses:
    - {{ .Values.metallb.ip.address }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: public
  namespace: {{ .Release.Namespace }}
spec:
  ipAddressPools:
    - public
---
