apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lakehouse
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
{{- range $i, $e := until 2 -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lakehouse-pv-{{ $i }}
spec:
  capacity:
    storage: 8Gi
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: lakehouse
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /kube/ecommerce/io/lakehouse/lakehouse-pv-{{ $i }}
  nodeAffinity:
{{ $.Values.master.volume | toYaml | nindent 4 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lakehouse-pvc-{{ $i }}
  namespace: io
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem
  storageClassName: lakehouse
  volumeName: lakehouse-pv-{{ $i }}
---
{{- end -}}
