apiVersion: v1
kind: ConfigMap
metadata:
  name: schema-registry-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: schema-registry
data:
  SCHEMA_REGISTRY_HOST_NAME: "schema-registry"
  SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR: {{ .Values.primary.replicas | quote }}
  SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "PLAINTEXT://cluster-kafka-bootstrap:9092"
  SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"
  SCHEMA_REGISTRY_DEBUG: "true"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: schema-registry
  namespace: {{ .Release.Namespace }}
  labels:
    app: schema-registry
spec:
  selector:
    matchLabels:
      app: schema-registry
  serviceName: schema-registry
  replicas: 1
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      containers:
        - name: schema-registry
          image: confluentinc/cp-schema-registry:7.6.0
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: schema-registry-config
          command:
            - bash
            - -c
            - unset SCHEMA_REGISTRY_PORT; /etc/confluent/docker/run
---
apiVersion: v1
kind: Service
metadata:
  name: schema-registry
  namespace: {{ .Release.Namespace }}
  labels:
    app: schema-registry
spec:
  type: LoadBalancer
  selector:
    app: schema-registry
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
