apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-spark
data:
  driver.yaml: |
    apiVersion: v1
    kind: Pod
    metadata:
      name: driver
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              preference:
                matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - worker
            - weight: 10
              preference:
                matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - master
      containers: [ ]
  executor.yaml: |
    apiVersion: v1
    kind: Pod
    metadata:
      name: executor
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              preference:
                matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - worker
            - weight: 10
              preference:
                matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - master
      containers: [ ]
---
