apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
nodeRegistration:
  name: master
  ignorePreflightErrors:
    - Swap
  criSocket: "unix:///var/run/crio/crio.sock"
  taints: [ ]  # allow schedule on control-plane node
  kubeletExtraArgs:
    node-ip: "192.168.1.8"
    hostname-override: "master"
localAPIEndpoint:
  advertiseAddress: "192.168.1.8"
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
networking:
  serviceSubnet: "192.168.8.0/18"
  podSubnet: "192.168.128.0/17"
  dnsDomain: "cluster.local"
controlPlaneEndpoint: "192.168.1.8"
apiServer:
  extraArgs:
    enable-admission-plugins: "NodeRestriction,PodNodeSelector,PodTolerationRestriction"
  certSANs:
    - "192.168.1.8"
clusterName: "kubernetes"
---
