global: { }

master:
  affinity: &masterAffinity
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/role
                operator: In
                values:
                  - master

  selector: &masterSelector
    kubernetes.io/hostname: master

  volume: &masterVolume
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/role
              operator: In
              values:
                - master

worker:
  affinity: &workerAffinity
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 50
          preference:
            matchExpressions:
              - key: kubernetes.io/role
                operator: In
                values:
                  - worker
        - weight: 10
          preference:
            matchExpressions:
              - key: kubernetes.io/role
                operator: In
                values:
                  - master

notebook:
  service:
    host: 192.168.1.89
