apiVersion: v2
name: monitor
description: A Helm chart for Kubernetes

type: application
version: 0.1.1
appVersion: "1.16.0"

dependencies:
  - alias: promestack
    version: 61.2.0
    name: kube-prometheus-stack
    condition: promestack.enabled
    repository: https://prometheus-community.github.io/helm-charts
