apiVersion: v2
name: network
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - alias: calico
    version: 3.28.1
    name: tigera-operator
    condition: calico.enabled
    repository: "https://projectcalico.docs.tigera.io/charts"

  - name: metallb
    version: 0.14.5
    condition: metallb.enabled
    repository: "https://metallb.github.io/metallb"
