apiVersion: v2
name: airflow
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: airflow
    version: 8.9.0
    condition: airflow.enabled
    repository: https://airflow-helm.github.io/charts
